-- CreateTable
CREATE TABLE `extracciones` (
    `idextracciones` INTEGER NOT NULL AUTO_INCREMENT,
    `rfc` VARCHAR(20) NULL,
    `razonsocial` VARCHAR(300) NULL,
    `direccionfiscal` VARCHAR(400) NULL,
    `fechainscripcion` VARCHAR(45) NULL,
    `urlconstancia` VARCHAR(300) NULL,
    `seriename` VARCHAR(45) NULL,
    `fechaemision` VARCHAR(45) NULL,
    `datefield` VARCHAR(45) NULL,
    `urlcertificado` VARCHAR(300) NULL,
    `direction` VARCHAR(300) NULL,
    `holder` VARCHAR(300) NULL,
    `expired` VARCHAR(300) NULL,
    `urlcomprobante` VARCHAR(300) NULL,
    `actanumber` VARCHAR(300) NULL,
    `notenumber` VARCHAR(300) NULL,
    `dateconstitution` VARCHAR(300) NULL,
    `altadate` VARCHAR(300) NULL,
    `activity` VARCHAR(300) NULL,
    `urlactacons` VARCHAR(300) NULL,
    `namefull` VARCHAR(300) NULL,
    `curp` VARCHAR(300) NULL,
    `porcentaje` VARCHAR(300) NULL,
    `ifeurl1` VARCHAR(300) NULL,
    `namefull2` VARCHAR(300) NULL,
    `curp2` VARCHAR(300) NULL,
    `porcentaje2` VARCHAR(300) NULL,
    `ifeurl2` VARCHAR(300) NULL,
    `namefull3` VARCHAR(300) NULL,
    `curp3` VARCHAR(300) NULL,
    `porcentaje3` VARCHAR(300) NULL,
    `ifeurl3` VARCHAR(300) NULL,
    `curp4` VARCHAR(300) NULL,
    `namefull4` VARCHAR(300) NULL,
    `ifeurl4` VARCHAR(300) NULL,
    `fechainsercion` VARCHAR(45) NULL,

    PRIMARY KEY (`idextracciones`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `kavakpoc` (
    `idkavakpoc` INTEGER NOT NULL AUTO_INCREMENT,
    `campo1` VARCHAR(300) NULL,
    `campo2` VARCHAR(300) NULL,
    `campo3` VARCHAR(300) NULL,
    `campo4` VARCHAR(300) NULL,
    `campo5` VARCHAR(300) NULL,
    `campo6` VARCHAR(300) NULL,
    `campo7` VARCHAR(300) NULL,
    `campo8` VARCHAR(300) NULL,
    `campo9` VARCHAR(300) NULL,
    `campo10` VARCHAR(300) NULL,
    `campo11` VARCHAR(300) NULL,
    `campo12` VARCHAR(300) NULL,
    `campo13` VARCHAR(300) NULL,
    `campo14` VARCHAR(300) NULL,
    `campo15` VARCHAR(300) NULL,
    `campo16` VARCHAR(300) NULL,
    `campo17` VARCHAR(300) NULL,
    `campo18` VARCHAR(300) NULL,
    `campo19` VARCHAR(300) NULL,
    `campo20` VARCHAR(300) NULL,
    `campo21` VARCHAR(300) NULL,
    `campo22` VARCHAR(300) NULL,
    `campo23` VARCHAR(300) NULL,
    `campo24` VARCHAR(300) NULL,
    `campo25` VARCHAR(300) NULL,
    `campo26` VARCHAR(300) NULL,
    `campo27` VARCHAR(300) NULL,
    `campo28` VARCHAR(300) NULL,
    `campo29` VARCHAR(300) NULL,
    `campo30` VARCHAR(300) NULL,
    `campo31` VARCHAR(300) NULL,
    `campo32` VARCHAR(300) NULL,
    `campo33` VARCHAR(300) NULL,
    `campo34` VARCHAR(300) NULL,
    `campo35` VARCHAR(300) NULL,
    `campo36` VARCHAR(300) NULL,
    `campo37` VARCHAR(300) NULL,
    `campo38` VARCHAR(300) NULL,
    `campo39` VARCHAR(300) NULL,
    `campo40` VARCHAR(300) NULL,
    `campo41` VARCHAR(300) NULL,
    `campo42` VARCHAR(300) NULL,
    `campo43` VARCHAR(300) NULL,
    `campo44` VARCHAR(300) NULL,
    `campo45` VARCHAR(300) NULL,
    `campo46` VARCHAR(300) NULL,
    `campo47` VARCHAR(300) NULL,
    `campo48` VARCHAR(300) NULL,
    `campo49` VARCHAR(300) NULL,
    `campo50` VARCHAR(300) NULL,
    `campo51` VARCHAR(300) NULL,

    PRIMARY KEY (`idkavakpoc`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `registros` (
    `idRegister` INTEGER NOT NULL AUTO_INCREMENT,
    `id_user` INTEGER NOT NULL,
    `createdAt` DATETIME(0) NULL DEFAULT CURRENT_TIMESTAMP(0),
    `talon_name` VARCHAR(255) NULL,
    `calcomania_verificacion_name` VARCHAR(255) NULL,
    `tarjeta_circulacion_name` VARCHAR(255) NULL,
    `placa_auto_name` VARCHAR(255) NULL,
    `placa_engomado_name` VARCHAR(255) NULL,
    `vin_parabrisas_name` VARCHAR(255) NULL,
    `vin_carroceria_name` VARCHAR(255) NULL,
    `no_motor_name` VARCHAR(255) NULL,
    `calcomania_repuve_name` VARCHAR(255) NULL,
    `tacometro_name` VARCHAR(255) NULL,
    `vin_escanner_name` VARCHAR(255) NULL,
    `km_escanner_name` VARCHAR(255) NULL,

    PRIMARY KEY (`idRegister`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
